# Generated by Django 4.1 on 2022-10-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha_reserva', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_persona', models.IntegerField(max_length=15)),
                ('estado', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=50)),
            ],
        ),
    ]
